[package]
name = "torrent"
version = "0.1.0"
authors = ["Brandon Kase <brandon.kase@gmail.com>"]

[dependencies]
nom = "~1.0.0"
url = "0.5.2"
rust-crypto = "^0.2"
rotor-stream = "0.4.0"
rotor-http = "0.5.0"
rotor = "0.5.0"
time = "0.1.34"
httparse = "1.1.0"
rand = "^0.3"
bit-set = "^0.3"

